### ISSUE TITLE
pypi install possibly broken

### ISSUE THREAD

**Issue by abshkd** [wilsaj/flask-admin-old#33]
This is the output from easy_install flask-admin using flask 0.8

<pre>
Searching for flask-admin
Reading http://pypi.python.org/simple/flask-admin/
Reading https://github.com/wilsaj/flask-admin/
Best match: Flask-Admin 0.3.0
Downloading http://pypi.python.org/packages/source/F/Flask-Admin/Flask-Admin-0.3
.0.tar.gz#md5=641c4caaa66aed3e15b67660d1e647d6
Processing Flask-Admin-0.3.0.tar.gz
Running Flask-Admin-0.3.0\setup.py -q bdist_egg --dist-dir c:\users\abhishek\app
data\local\temp\easy_install-5o9g6k\Flask-Admin-0.3.0\egg-dist-tmp-ehn5np
Traceback (most recent call last):
  File "c:\Python27\Scripts\easy_install-script.py", line 8, in <module>
    load_entry_point('setuptools==0.6c11', 'console_scripts', 'easy_install')()
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
1712, in main
    with_ei_usage(lambda:
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
1700, in with_ei_usage
    return f()
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
1716, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "c:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
211, in run
    self.easy_install(spec, not self.no_deps)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
446, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
476, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
655, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
930, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
919, in run_setup
    run_setup(setup_script, args)
  File "c:\Python27\lib\site-packages\setuptools\sandbox.py", line 62, in run_se
tup
    lambda: execfile(
  File "c:\Python27\lib\site-packages\setuptools\sandbox.py", line 105, in run
    return func()
  File "c:\Python27\lib\site-packages\setuptools\sandbox.py", line 64, in <lambd
a>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 50, in <module>
  File "c:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 167
, in run
    self.run_command("egg_info")
  File "c:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 177,
 in run
    self.find_sources()
  File "c:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 252,
 in find_sources
    mm.run()
  File "c:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 308,
 in run
    self.read_template()
  File "c:\Python27\lib\site-packages\setuptools\command\sdist.py", line 157, in
 read_template
    _sdist.read_template(self)
  File "c:\Python27\lib\distutils\command\sdist.py", line 315, in read_template
    self.filelist.process_template_line(line)
  File "c:\Python27\lib\distutils\filelist.py", line 118, in process_template_li
ne
    action, patterns, dir, dir_pattern = self._parse_template_line(line)
  File "c:\Python27\lib\distutils\filelist.py", line 97, in _parse_template_line

    dir = convert_path(words[1])
  File "c:\Python27\lib\distutils\util.py", line 202, in convert_path
    raise ValueError, "path '%s' cannot end with '/'" % pathname
ValueError: path 'flask_admin/' cannot end with '/'
</pre>

**Comment by wilsaj** [comment]
Hi abshkd - thanks for reporting.

This is a problem on windows, but has been fixed in the dev version if you install from source. I'll try to upload a new release on pypi in the next few days.

**Comment by wilsaj** [comment]
Ok, there's new release on pypi. Can you try again and let me know how that goes?

**Comment by abshkd** [comment]
hi wilsaj, yes it works perfectly.
thanks.

**Comment by wilsaj** [comment]
Great. Thanks for reporting & testing!
